### ISSUE TITLE
Convert_lite not working

### ISSUE THREAD

**Issue by innodeltech** [sunnysoni97/iplantify_droid#3]
Error : 
File name : data_training/convert_lite.py
OSError: SavedModel file does not exist at:  iplantify_droid/data_training/{saved_model.pbtxt|saved_model.pb}

**Comment by sunnysoni97** [comment]
The issue is self explanatory. Going back to the instruction manual given in the readme, it states that you have to first make your own dataset, i.e. images placed in the appropriate folder according to their classification identifier, then being trained using retrain.py.

It gives you two or one file as output : saved_model.pbtxt and saved_model.pb containing the tf graph for the desktop tf version.

You will have to then place these trained graph files in the exact folder as mentioned in your error "OSError: SavedModel file does not exist at: iplantify_droid/data_training/{saved_model.pbtxt|saved_model.pb}"

Then you can use convert_lite.py to get a tf lite graph, which can be replaced in the android resource folder, where the tflite graph is stored. Hope this helps you!

P.S. It wasn't possible for me to upload the entire training data set in its original form, as they were thousands of images scrapped over the web and was large in size. So you will have to make your own dataset according to your needs.

**Comment by innodeltech** [comment]
Which TensorFlow version is compatible with in this project?

**Comment by sunnysoni97** [comment]
I made it on 2.1, which was available at that time. It should probably work fine with 2.0+ any versions :)

**Comment by innodeltech** [comment]
Thank you :)
